 [build.environment]
  VITE_API_URL = "https://smartbrain-serverside.onrender.com"
  VITE_FIREBASE_API_KEY = "AIzaSyBFA6fqAK90BNfha8tgPXo4Qla70hFN0es"
  VITE_FIREBASE_AUTH_DOMAIN = "smartbrains-6b54b.firebaseapp.com"
  VITE_FIREBASE_DATABASE_URL = "https://smartbrains-6b54b-default-rtdb.firebaseio.com"
  VITE_FIREBASE_PROJECT_ID = "smartbrains-6b54b"
  VITE_FIREBASE_STORAGE_BUCKET = "smartbrains-6b54b.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "532046064190"
  VITE_FIREBASE_APP_ID = "1:532046064190:web:992c585455a9e61939bf6f"
